package com.opiframe.pojos;
// Generated 15.1.2016 12:05:47 by Hibernate Tools 4.3.1



/**
 * CourseStudents generated by hbm2java
 */
public class CourseStudents  implements java.io.Serializable {


     private Integer courseStudentsId;
     private Courses courses;
     private Students students;

    public CourseStudents() {
    }

    public CourseStudents(Courses courses, Students students) {
       this.courses = courses;
       this.students = students;
    }
   
    public Integer getCourseStudentsId() {
        return this.courseStudentsId;
    }
    
    public void setCourseStudentsId(Integer courseStudentsId) {
        this.courseStudentsId = courseStudentsId;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }




}


