package com.opiframe.pojos;
// Generated 15.1.2016 12:05:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private Integer courseId;
     private Teachers teachers;
     private String courseName;
     private Set courseStudentses = new HashSet(0);

    public Courses() {
    }

    public Courses(Teachers teachers, String courseName, Set courseStudentses) {
       this.teachers = teachers;
       this.courseName = courseName;
       this.courseStudentses = courseStudentses;
    }
   
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public Teachers getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Teachers teachers) {
        this.teachers = teachers;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public Set getCourseStudentses() {
        return this.courseStudentses;
    }
    
    public void setCourseStudentses(Set courseStudentses) {
        this.courseStudentses = courseStudentses;
    }




}


