package com.opiframe.pojos;
// Generated 13.1.2016 17:15:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Teachers generated by hbm2java
 */
public class Teachers  implements java.io.Serializable {


     private Integer teacherId;
     private String teacherName;
     private String teacherPosition;
     private Set courseses = new HashSet(0);

    public Teachers() {
    }

    public Teachers(String teacherName, String teacherPosition, Set courseses) {
       this.teacherName = teacherName;
       this.teacherPosition = teacherPosition;
       this.courseses = courseses;
    }
   
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
    public String getTeacherPosition() {
        return this.teacherPosition;
    }
    
    public void setTeacherPosition(String teacherPosition) {
        this.teacherPosition = teacherPosition;
    }
    public Set getCourseses() {
        return this.courseses;
    }
    
    public void setCourseses(Set courseses) {
        this.courseses = courseses;
    }




}


